### ISSUE TITLE
AttributeError: type object 'Server' has no attribute 'reason'

### ISSUE THREAD

**Issue by ductridev** [miguelgrinberg/Flask-SocketIO#2124]
**Describe the bug**
Just a weird error after upgrade flask-socketio to 5.5.0 by upgrading flask-socketio version
`flask-socketio==5.5.0`

**To Reproduce**
1. Change in requirements: `flask-socketio=5.5.0`.
2. Run `pip install -r requirements.txt`
3. Start server

**Expected behavior**
It should be fine like previous versions.

**Logs**
```
Traceback (most recent call last):
  File "/home/container/veware-payment/index.py", line 16, in <module>
    from flask_socketio import SocketIO, send, emit
  File "/home/container/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 52, in <module>
    class SocketIO:
  File "/home/container/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 168, in SocketIO
    reason = socketio.Server.reason
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Server' has no attribute 'reason'
```
**Additional context**
Here is example code:
```
from flask import Flask
from flask_qrcode import QRcode
from flask_socketio import SocketIO, send, emit

app = Flask(__name__)
QRcode(app)
socketio = SocketIO(app, cors_allowed_origins="*")

app.secret_key = "xxxxx-xxxxxx"

@socketio.on('message')
def handle_message(message):
    if (message == 'ping'):
        send('pong')
    else:
        send('Unknow message')


@socketio.on('connect')
def handle_message(connection):
    send(json.dumps({'sid': request.sid}))


if __name__ == '__main__':
    socketio.run(app, port=25907, debug=True,
                 host='0.0.0.0', use_reloader=True)
    # socketio.run(app, host='0.0.0.0', port=25886)
```

**Comment by ductridev** [comment]
It seems like a problem with cached packages, I delete the cache then try to install it all again and it works!
